### ISSUE TITLE
Error: cb(error); undefined is not a function

### ISSUE THREAD

**Issue by Baudin999** [nospaceships/node-os-service#10]
Hi, I'm trying to get this module to work. I have a case which involves me having to run a long lasting service on OSX, Windows or Linux. I'm running the following code on my machine:

```
var service = require("os-service"),
    fs = require('fs'),
    logStream = fs.createWriteStream("carlos-service.log");

service.add("carlos-service");
service.run(logStream, function() {
    logStream.write("stopping the application");
    service.stop();
});
```

But I get the following error:

```
/usr/local/bin/node --debug-brk=58396 --nolazy tests/service-test.js
Debugger listening on port 58396
/Users/carloskelkboom/Documents/Work/Diophantic/Beks/CreditTools/node_modules/os-service/index.js:235
                cb(error);
                ^
TypeError: undefined is not a function
    at /Users/carloskelkboom/Documents/Work/Diophantic/Beks/CreditTools/node_modules/os-service/index.js:235:5
    at fs.js:1077:21
    at FSReqWrap.oncomplete (fs.js:95:15)

Process finished with exit code 1
```

Am I doing something wrong? I'm running this code on OSX 10.10.5 I believe and using node 0.12.2
If there is anything more I can do to help, or if you need more information, please let me know.

**Comment by stephenwvickers** [comment]
Hi Carlos,

You need to provide a callback to the service.add() function:

https://www.npmjs.com/package/os-service#service-add-name-options-cb

In addition, this module has not been tested to work with OS X.

Regards

Steve
