### ISSUE TITLE
Doesn't install

### ISSUE THREAD

**Issue by bradennapier** [nospaceships/node-os-service#11]
Says I need python to install this?  Nothing in documentation says it works using python.

**Comment by bradennapier** [comment]
![image](https://cloud.githubusercontent.com/assets/15365418/11004045/d0495db2-846a-11e5-8942-a3e89fdddf30.png)

**Comment by stephenwvickers** [comment]
Are you serious?

**Comment by bradennapier** [comment]
I believe so?  Upon looking at your npm.js documentation you discuss needing node-gyp setup - that is not included in your github documentation.  I will do that now - which I know does require Python.

**Comment by stephenwvickers** [comment]
The README.md indicates that node-gyp will be used to install the module.

**Comment by bradennapier** [comment]
So in order to distribute this - does any computer running the script need to install the Visual Studio as well?  Is there a way to package it into an installable without it being 6-7 gb?

**Comment by bradennapier** [comment]
Very sorry for my ignorance.

**Comment by stephenwvickers** [comment]
No that's okay, there are two ways to do this. I'm off out the door right now and I will get the details for you tomorrow.

I've used this in shrink wrapped products for Linux and windows, and I can share how that was done.

**Comment by bradennapier** [comment]
Ok great.  I basically want to have a small script that someone can install which runs system monitoring and reports it to their web portal for remote management of many devices.  We do it already with a Linux TCL Process but this is appealing to do via Node / JS.  

We simply need Websocket & HTTP running in the script pretty much.

**Comment by stephenwvickers** [comment]
So, there are two methods we've used to ship pre-compiled binaries.

Firstly, is to "npm install" the "os-service" module, which will go into the "node_modules" directory.  We would then commit that into the local repository, which would then be available once copied/clone'd on another production server.

Secondly, we would do the same but this time for all "node_modules", and then use a simple "NSIS" installer to simply install the code and services.  This is a little more work, but it's ideal for less experienced end-users.

From what I understand there is also a Node.js project which aims to provide access to pre-compiled binary addons such as this one.
