### ISSUE TITLE
Add service that runs under a particular user account

### ISSUE THREAD

**Issue by sellis** [nospaceships/node-os-service#12]
Is it possible to use this module to add a service that runs under a particular user account?

**Comment by stephenwvickers** [comment]
Yes, this is possible.

The CreateService function on Windows allows us to specify a username and password to logon with, and for Linux we simply set the UID/etc.

I will look at adding this into the next release, I don't have dates for that yet though.

**Comment by stephenwvickers** [comment]
Implemented in 1.2.0 which has been published to npm.
