### ISSUE TITLE
Fails to Install - error in win_delay_load_hook

### ISSUE THREAD

**Issue by slmmm** [nospaceships/node-os-service#18]
After having installed python and windows-build-tools and then calling install for os-service, receiving error
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type modifiers [C:\Users\me\Documents\myproject\node_modules\os-service\build\service.vcxproj]

Installed versions:  node v6.2.2 & npm 3.9.5
Running on Windows 10 (Windows_NT 10.0.10586)

How can I resolve this issue?

**Comment by stephenwvickers** [comment]
Hi,

A quick google revealed this:

https://github.com/nodejs/node-gyp/issues/972

I don't believe it is an issue with this module.

Steve
