### ISSUE TITLE
Issue with application that calls child_process.fork()

### ISSUE THREAD

**Issue by dtopham75** [nospaceships/node-os-service#19]
I'm trying to use os-service on Windows with an application that uses child_process.fork() to spin up additional invocations of Node to do work.

When the application is run from the console, it works. When it runs as a service, the child process terminates the first time it tries to write to stdout using console.log.

To demonstrate this, I've modified the periodic-logger.js example, see attached tgz. 

It still does what it did before - calls setInterval to write to the console every second. But it also calls child_process.fork() to create a child process using the file 'child.js', which does exactly the same thing with setInterval as the parent process.

I've also added some 'brute force' logging using appendFileSync to show what's going on. 

**When this is run from the command line with --run:**
- The console.log output from the parent is written to the log file periodic-logger.js.log, as expected.
- The console.log output from the child is written to the standard output of the parent. This is not ideal, but I suppose the child process can't inherit the parent's 'stdout' if it now refers to a stream defined in the parent process (I assume the real stdout is handled in fork() a special case). 

**When this is run  as a Windows Service:**
- The console.log output from the parent is written to the log file periodic-logger.js.log, as expected.
- The first attempt to write console.log output in the child process causes the child process to terminate unexpectedly.  This sounds strange but seems to be the case. Putting a try/catch block around it yields the error 'Error: Implement me. Unknown stream file type!'.

It's not clear why the behaviour differs between the two modes. I've tried this with both Node 4.4.7 and 0.12.15.

A workaround is to specify the {silent: true} option when calling child_process.fork(), but that just suppresses the child process output, which is also not ideal. 

Any other suggestions appreciated. 

[os-service-test.tar.gz](https://github.com/stephenwvickers/node-os-service/files/375914/os-service-test.tar.gz)

**Comment by stephenwvickers** [comment]
Can you try sending the child processes standard output/error to a file?

**Comment by stephenwvickers** [comment]
Closing, no further information provided.

If this is still an issue please re-open.
