### ISSUE TITLE
Q: How to safely uninstall a service?

### ISSUE THREAD

**Issue by seangenabe** [nospaceships/node-os-service#20]
How would I go about safely uninstalling a service, i.e. stop then uninstall? 

In `remove`'s doc, it says that

> The service must be in a stopped state for it to be removed

In `stop`'s doc:

> the function will not return

It seems it's impossible to stop + uninstall with the current API, isn't it?

**Comment by stephenwvickers** [comment]
Hi,

Yes, you are correct, the module does not provide any service start/stop ability from a service control management, only the ability to install, uninstall and run a process as a service.

It is the same problem for when you initially install the service, you must use a service control program to start the service, when uninstalling you must signal the service to stop and then remove it.

The command "net stop <service-name>" can be used to stop the service.
