### ISSUE TITLE
Error 2186 on Windows service start

### ISSUE THREAD

**Issue by pstkweb** [nospaceships/node-os-service#21]
I have an app that launch a SocketIO server and register it as a service with your tool. 

On unix platform there isn't any problem but on Windows Server 2012 the service is registered but the `NET START service-name` command fail with a 2186 error code and if I use the Services GUI to launch it I have a 1053 error.

Here how I register it (standalone script) : 

``` js
if (process.argv[2] == '--add') {
    service.add(SERVICE_NAME, { programPath: path.join(__dirname, "server.js") }, function(error){
        if (error) {
            console.trace(error);
        } else {
            console.log("Service successfully added");
        }
    });
} else if (process.argv[2] == '--remove') {
    service.remove(SERVICE_NAME, function(error){
        if (error) {
            console.trace(error);
        }
    });
}
```

And a piece of my `server.js` script : 

``` js
var config = require('./config'),
    mysql = require('mysql'),
    connection = mysql.createConnection(config.MYSQL),
    app = require('express')(),
    server = require('http').Server(app),
    io = require('socket.io')(server),
    log4js = require('log4js');

// Logger configuration
log4js.configure({
    appenders: [
        {type: 'console'},
        {type: 'file', filename: 'websockets.log'}
    ]
});
var logger = log4js.getLogger();

// HTTP server
server.listen(config.LISTEN_PORT);

// MySQL connection
connection.connect(function (err) {
    if (err) {
        logger.error('Connection error: ' + err);
        return;
    }

    logger.info("MySQL connected as: " + connection.threadId);
});

io.on('connection', function (socket) {
    // messages send/receive
});
```

Is there something wrong with my code?

**Comment by stephenwvickers** [comment]
Hi,

Can you open the Windows Service Controller program and view the properties of your service.  Use the full command line and attempt to run your program from the command prompt, does the program run that way?

It could be that you simply need to execute `process.chdir(__dirname)` at the very top of the server.js script before your program does anything.

Steve

**Comment by pstkweb** [comment]
Launching the full command line works in the command prompt. I try adding `process.chdir(__dirname)` on head but it doesn't help.

Error reproduced on Windows 10.

**Comment by stephenwvickers** [comment]
Just realised, you are not using the module correctly.

You are missing something like this:

``` javascript
var logStream = fs.createWriteStream ("my-service.log");

service.run (logStream, function () {
    console.log ("stop request received");
    service.stop ();
});
```

Do this BEFORE the log4js configuration.

**Comment by pstkweb** [comment]
By the doc I though it was not required when we split the service itself and the service manager but it still doesn't work, the full command line works in command prompt.

**Comment by wayne-nlt** [comment]
I am receiving the same error, my service is just a service.run call.  
I am on windows 10 too, tried with node 4.4.4 and 6.9.1
The command works fine from the command line.

**Comment by pstkweb** [comment]
I tried with node 4.6.1, 5.3.0 and 7.0.0. The command always works fine from the command line.

**Comment by stephenwvickers** [comment]
@pstkweb I believe this is clear in the docs under the "Batch Service Creation" section, where the code to add and remove services is seperated out to a dedicated program which results in a service program simiarl to this snippet:

``` javascript
var logStream = fs.createWriteStream (process.argv[1] + ".log");

service.run (logStream, function () {
    service.stop (0);
});

// Run service program code...
```

@wayne-nlt Can you post your program so I can test using it? Thanks.

**Comment by stephenwvickers** [comment]
Also, another question for all, are you using the local system account, or did you specify a username/password when you created the service?

**Comment by wayne-nlt** [comment]
I have been playing with this again today and things are going better, I think there must have been an issue with the log file, permissions or something.
I was running without specifying any username/password.

**Comment by pstkweb** [comment]
I am using the local system account.

**Comment by wayne-nlt** [comment]
I'm not sure if this is related to this or not, but I am getting a segfault in my node process when I call service.run

Here is the service:

```
var service = require("os-service");
var fs = require ("fs");
var path = require ("path");

var logStream = fs.createWriteStream (path.join(process.env.ProgramData, "NLT", "Logs", "test-log.log"));
// Must be first call in the file
service.run (logStream, function () {
  console.log ("stop request received");
  clearInterval(interval);
});

var SegfaultHandler = require('segfault-handler');
SegfaultHandler.registerHandler("crash.log");

interval = setInterval(() => {
}, 60000);
```

When I run it as administrator from a command prompt I get the following dump:

```
PID 4612 received SIGSEGV for address: 0xb97f7788
SymInit: Symbol-SearchPath: '.;C:\Program Files (x86)\NLT\bin;C:\Program Files\nodejs;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'Wayne'
OS-Version: 10.0.14393 () 0x100-0x1
c:\program files (x86)\nlt\bin\node_modules\segfault-handler\src\stackwalker.cpp (941): StackWalker::ShowCallstack
c:\program files (x86)\nlt\bin\node_modules\segfault-handler\src\segfault-handler.cpp (116): segfault_handler
00007FFBBC6AAAC0 (ntdll): (filename not available): RtlInitializeCriticalSection
00007FFBBC6883CB (ntdll): (filename not available): RtlImageNtHeaderEx
00007FFBBC68A3E9 (ntdll): (filename not available): RtlRaiseException
00007FFBB97F7788 (KERNELBASE): (filename not available): RaiseException
00007FFBBA298871 (RPCRT4): (filename not available): RpcRaiseException
00007FFBBA298834 (RPCRT4): (filename not available): RpcRaiseException
00007FFBBA29909E (RPCRT4): (filename not available): NdrGetUserMarshalInfo
00007FFBBA2925DA (RPCRT4): (filename not available): NdrpClientCall2
00007FFBBA29153F (RPCRT4): (filename not available): NdrClientCall2
00007FFBB9C8EEE9 (sechost): (filename not available): StartServiceCtrlDispatcherW
00007FFBB9C98614 (sechost): (filename not available): StartServiceCtrlDispatcherA
c:\program files (x86)\nlt\bin\node_modules\os-service\src\service.cc (92): run_thread
00007FFBBC528364 (KERNEL32): (filename not available): BaseThreadInitThunk
00007FFBBC6A5E91 (ntdll): (filename not available): RtlUserThreadStart
```

Running node 6.9.1.
os-service 1.3.0

It had been working fine, but it seemed to stop working randomly, now it isn't working at all.

**Comment by stephenwvickers** [comment]
Hi @wayne-nlt 

I think this would be unrelated.

Generally, when node programs using this module stop "randomly" it is because they emit a unhandled exception or promise rejection.

Steve

**Comment by batmanppc** [comment]
node 6.9.1.
os-service 1.3.0

Hello

I am having the same issue with os-service on Windows 7 as @pstkweb. However, I am using the method of having the program add itself as a service when passed --add and using --run to actually run the service. The program works without issue when run from the console. I've confirmed that file permissions for the log files are correct.

Is there anywhere else I can look for errors?

```
....
if(process.argv[2] == '--run')
{
    const processname = path.basename(process.argv[1], path.extname(process.argv[1]));
    const stdout = fs.createWriteStream(path.join(process.env.ProgramData, module.exports.name, 'Logs') + processname + '.log');
    const stderr = fs.createWriteStream(path.join(process.env.ProgramData, module.exports.name, 'Logs') + processname + '-error.log');
    service.run(stdout, stderr, function() { service.stop(); });
}

main()

```

**Comment by batmanppc** [comment]
Figured it out. Do the absolute minimum required prior to calling service.run(). Loading of modules prior to this appear to increase the time before service.run() is listening for control and times out. Moving all my requires except the absolute essentials needed prior to service.run() after the call solved my issue.

**Comment by pstkweb** [comment]
Thanks @batmanppc by requiring only needed libraries (`fs` and `os-service`) it works well.

**Comment by rvmey** [comment]
Thank you!  This solved my problem too.  

The Windows service starts as long as I require most of my dependencies after the service.run() call.  

It works when I only do these things before service.run():
  process.chdir(__dirname);
  var fs = require('fs');
  var service = require ("os-service");

**Comment by wayne-nlt** [comment]
So it seems the call to run is very time sensitive. 
Maybe there is some way to emit a warning or error if the call to run is too slow?

**Comment by stephenwvickers** [comment]
I don't believe the run() call is very time sensitive, rather that you need to process.chdir(__dirname) before you call it.

I have also ran into issues with logging modules replacing file descriptors, but other than that I've not experienced any issues.

It's quite difficult to see if anyone is still experiencing an issue.  I'll mark this as closed, and if anyone has any issues still, please comment on the ticket and I will look to re-open.

**Comment by batmanppc** [comment]
@stephenwvickers the run() call itself isn't time sensitive. It's the timing up to when run() is called and listening for communication from Windows. Loading up modules and other items before calling run() exceeds whatever timeout in the services process. So not really a bug/issue in the module but something to note in using the module.

**Comment by stephenwvickers** [comment]
@batmanppc I undestand.  Like the Win32 API calls, the service should be started before doing any tasks.  Next time I am updating the docs I will make a note of this.
