### ISSUE TITLE
The service stops as soon as I call my script

### ISSUE THREAD

**Issue by wmmihaa** [nospaceships/node-os-service#22]
I get the service installed correctly and all works good using the setInterval sample. However, the service immediately shouts down as soon as I call my script. I've tried to set the **programPath** parameter, but then it doesn't start at all.

To get around the issue, I tried starting it from within the setInterval:

```js
        service.run(logStream, function () {
            service.stop(0);
        });
        setInterval(function () {
            console.log('This is called');
            runMyScript(function (message) {
                console.log('This is not');
            });
        }, 1000);
```
But now it shuts down immediately :( I realize it might be related to my script, but it runs perfectly using the *--run* option. Are there any restrictions on how my application is built?

**Comment by stephenwvickers** [comment]
Can you post the entire programming including the runMyScript code. Thanks like logging and requires are very important.

Also, a process.chdir(__dirname) must be done at the top of the script, otherwise your program is started in the wrong directory.

**Comment by wmmihaa** [comment]
Thanks for getting back to me Stephen.
The "script" is a fairly large [application](https://github.com/microServiceBus/microservicebus.node), but the runMyScript method looks like this:

``` js
function runMyScript(callback) {
    // Prevent the service from being started more than once
    if (microServiceBusHost) {       
        return;
    }

    microServiceBusHost = 1;

    var utils = require('./Utils.js');
    var data = fs.readFileSync(__dirname + '/settings.json');
    settings = JSON.parse(data);
    settings.log = "microServiceBus.log"
    utils.saveSettings(settings, function () {
        console.log("Never happends");
        var MicroServiceBusHost = require("./microServiceBusHost.js");
        microServiceBusHost = new MicroServiceBusHost(settings);
        microServiceBusHost.Start();
    });
};
```

I do have the **process.chdir(__dirname)** at the top of the script.

**Comment by wmmihaa** [comment]
Never mind... My bad... the settings.json file was corrupt :(
