### ISSUE TITLE
Specify restart options

### ISSUE THREAD

**Issue by marcinbudny** [nospaceships/node-os-service#32]
It would be very useful to be able to specify restart options for the service installed in the OS. In Windows this would mean selecting recovery options for first failure, second failure, subsequent failure (could be simplified to just two options: restart or do nothing). For Linux and systemd this would mean setting the `Restart` option in `Service` section of the configuration file.

**Comment by stephenwvickers** [comment]
Having reviewed this I am not going to implement this feature.  There are plenty of nanny frameworks which do a better job at providing this feature than both Linux and Windows can provide.
