### ISSUE TITLE
Error: OpenSCManager() failed: Access is denied.

### ISSUE THREAD

**Issue by jdshin123** [nospaceships/node-os-service#42]
Hello, i get this error message "Error: OpenSCManager() failed: Access is denied. " and i was wondering how to circumvent this. Was reading through some earlier issues.. and still kind of lost. 

Win 10.
nmp 6.4.1

**Comment by stephenwvickers** [comment]
Hi @jdshin123 

When installing/uninstalling a service you will need to run the script with administrative privileges, or with the relevant privileges to do so.

Steve

**Comment by jdshin123** [comment]
@stephenwvickers  Thanks a lot! One more quick question... is it possible to implement/use os-service not using admin privileges?

**Comment by stephenwvickers** [comment]
So, you can run the service as a different user by specifying the `username` and `password` options when you create the service, i.e.:

```
var options = {
    ...
    username: ".\Stephen Vickers",
    password: "MyPassword :)",
    ...
}

service.add ("my-service", options, function(error) {
    if (error)
        console.trace(error)
})
```
