### ISSUE TITLE
Support Node.js 12.x

### ISSUE THREAD

**Issue by manuelfrey** [nospaceships/node-os-service#50]
We used the node module os-service in our project sucessfully. Yesterday I upgraded NodeJS version to Node 12.13 LTS, I also installed "additional Tools for Node.JS" (BuildTools). I am using Windows 10 Pro.

If I now try to add os-service to any project I got the following error log:  Are there any plans to update os-service to run with NodeJS 12 or is something else wrong?

Thanks in advance for assistance

Build-Log:

> os-service@2.1.3 install D:\Testprogramme\test\fb\node_modules\os-service
> node-gyp rebuild

D:\Testprogramme\test\fb\node_modules\os-service>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  service.cc
  pthread.cc
  win_delay_load_hook.cc
d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan_converters_43_inl.h(22): warning C4996: 'v8::Value::ToBoolean': wurde als veraltet deklariert (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
  c:\users\user\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2567): note: Siehe Deklaration von "v8::Value::ToBoolean" (Quelldatei wird kompiliert ..\src\service.cc)
d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan_converters_43_inl.h(40): warning C4996: 'v8::Value::BooleanValue': wurde als veraltet deklariert (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
  c:\users\user\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(2605): note: Siehe Deklaration von "v8::Value::BooleanValue" (Quelldatei wird kompiliert ..\src\service.cc)
d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan_implementation_12_inl.h(103): error C2664: "v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>,v8::FunctionCallback,v8::Local<v8::Value>,int,v8::ConstructorBehavior,v8::SideEffectType)" : Konvertierung von Argument 1 von "v8::Isolate *" in "v8::Local<v8::Context>" nicht möglich (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
  d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan_implementation_12_inl.h(105): note: Quelltyp konnte von keinem Konstruktor angenommen werden, oder die Überladungsauflösung des Konstruktors ist mehrdeutig (Quelldatei wird kompiliert ..\src\service.cc)
d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan_implementation_12_inl.h(337): error C2660: "v8::StringObject::New": Funktion akzeptiert keine 1 Argumente (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
  c:\users\user\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(5426): note: Siehe Deklaration von "v8::StringObject::New" (Quelldatei wird kompiliert ..\src\service.cc)
d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan_implementation_12_inl.h(337): error C2059: Syntaxfehler: ")" (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan.h(1034): error C2661: "v8::Value::ToString": Keine überladene Funktion akzeptiert 0 Argumente (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan.h(1044): error C2664: "int v8::String::WriteUtf8(v8::Isolate *,char *,int,int *,int) const" : Konvertierung von Argument 1 von "char *" in "v8::Isolate *" nicht möglich (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
  d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan.h(1044): note: Die Typen, auf die verwiesen wird, sind nicht verknüpft; die Konvertierung erfordert einen reinterpret_cast-Operator oder eine Typumwandlung im C- oder Funktionsformat. (Quelldatei wird kompiliert ..\src\service.cc)
d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan.h(1818): warning C4996: 'v8::Object::Set': wurde als veraltet deklariert (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
  c:\users\user\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(3402): note: Siehe Deklaration von "v8::Object::Set" (Quelldatei wird kompiliert ..\src\service.cc)
d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan.h(1824): warning C4996: 'v8::Object::Set': wurde als veraltet deklariert (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
  c:\users\user\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(3402): note: Siehe Deklaration von "v8::Object::Set" (Quelldatei wird kompiliert ..\src\service.cc)
d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan.h(1830): warning C4996: 'v8::Object::Set': wurde als veraltet deklariert (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
  c:\users\user\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(3411): note: Siehe Deklaration von "v8::Object::Set" (Quelldatei wird kompiliert ..\src\service.cc)
d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan.h(1836): warning C4996: 'v8::Object::Get': wurde als veraltet deklariert (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
  c:\users\user\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(3457): note: Siehe Deklaration von "v8::Object::Get" (Quelldatei wird kompiliert ..\src\service.cc)
d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan.h(1842): warning C4996: 'v8::Object::Get': wurde als veraltet deklariert (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
  c:\users\user\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(3457): note: Siehe Deklaration von "v8::Object::Get" (Quelldatei wird kompiliert ..\src\service.cc)
d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan.h(1847): warning C4996: 'v8::Object::Get': wurde als veraltet deklariert (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
  c:\users\user\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(3461): note: Siehe Deklaration von "v8::Object::Get" (Quelldatei wird kompiliert ..\src\service.cc)
d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan_object_wrap.h(24): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
          with
          [
              T=v8::Object
          ] (Quelldatei wird kompiliert ..\src\service.cc)
  d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan.h(1859): note: Siehe Deklaration von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>"
          with
          [
              T=v8::Object
          ] (Quelldatei wird kompiliert ..\src\service.cc)
d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan_object_wrap.h(67): warning C4996: 'v8::PersistentBase<v8::Object>::MarkIndependent': wurde als veraltet deklariert (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
  c:\users\user\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(563): note: Siehe Deklaration von "v8::PersistentBase<v8::Object>::MarkIndependent" (Quelldatei wird kompiliert ..\src\service.cc)
d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan_object_wrap.h(124): error C2039: "IsNearDeath": Ist kein Element von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>" [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
          with
          [
              T=v8::Object
          ] (Quelldatei wird kompiliert ..\src\service.cc)
  d:\testprogramme\test\fb\node_modules\os-service\node_modules\nan\nan.h(1859): note: Siehe Deklaration von "Nan::Persistent<v8::Object,v8::NonCopyablePersistentTraits<T>>"
          with
          [
              T=v8::Object
          ] (Quelldatei wird kompiliert ..\src\service.cc)
d:\testprogramme\test\fb\node_modules\os-service\src\service.h(26): error C2065: "Handle": nichtdeklarierter Bezeichner (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
d:\testprogramme\test\fb\node_modules\os-service\src\service.h(26): error C2275: "v8::Object": Ungültige Verwendung dieses Typs als Ausdruck (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
  c:\users\user\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(3400): note: Siehe Deklaration von "v8::Object" (Quelldatei wird kompiliert ..\src\service.cc)
d:\testprogramme\test\fb\node_modules\os-service\src\service.h(26): error C2065: "exports": nichtdeklarierter Bezeichner (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
d:\testprogramme\test\fb\node_modules\os-service\src\service.h(26): error C2182: "Init": Unzulässige Verwendung des Typs "void" (Quelldatei wird kompiliert ..\src\service.cc) [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
d:\testprogramme\test\fb\node_modules\os-service\src\service.cc(114): error C2065: "Handle": nichtdeklarierter Bezeichner [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
d:\testprogramme\test\fb\node_modules\os-service\src\service.cc(114): error C2275: "v8::Object": Ungültige Verwendung dieses Typs als Ausdruck [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
  c:\users\user\appdata\local\node-gyp\cache\12.13.0\include\node\v8.h(3400): note: Siehe Deklaration von "v8::Object"
d:\testprogramme\test\fb\node_modules\os-service\src\service.cc(114): error C2065: "exports": nichtdeklarierter Bezeichner [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
d:\testprogramme\test\fb\node_modules\os-service\src\service.cc(114): error C2182: "InitAll": Unzulässige Verwendung des Typs "void" [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
d:\testprogramme\test\fb\node_modules\os-service\src\service.cc(114): error C2448: "service::InitAll": Funktionsstil-Initialisierung scheint eine Funktionsdefinition zu sein [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]
d:\testprogramme\test\fb\node_modules\os-service\src\service.cc(137): warning C4312: "Typumwandlung": Konvertierung von "int" in größeren Typ "node::addon_register_func" [D:\Testprogramme\test\fb\node_modules\os-service\build\service.vcxproj]

**Comment by lselden** [comment]
Check out my pull request on this topic: https://github.com/nospaceships/node-os-service/pull/47 - If you need the project in short order you could pull from my git fork instead:
```json
{
  "dependencies": {
    "os-service": "https://github.com/lselden/node-os-service.git"
  }
}
```

**Comment by manuelfrey** [comment]
@Iselden
Thank you very much for your support. It works! :-)

**Comment by stephenwvickers** [comment]
This is fixed in 2.2.0 which is about to be pushed to npm.
