### ISSUE TITLE
Error occurs while stopping service from service.msc or using os-service

### ISSUE THREAD

**Issue by divishav** [nospaceships/node-os-service#51]
A service has been registered using os-service. When we try to stop it from service.msc or os-service code it throws the following error: windows could not stop the service On-Local computer

Error 1607: The process terminated unexpectedly.

The service is stopped. We are using Windows 10 with Node 10

**Comment by stephenwvickers** [comment]
Hi @divishav 

I have also noticed this starting to happen on my Windows 10 PC after the most recent update - I have no idea if it is related to that though.

Unfortunately, we massage the Win32 API into getting Node.js to run as a Windows service, so I am not sure if this problem can actually be fixed, at the least I cannot see where the issue could be and nothing I've changed so far has been able to fix it.

It could be related by the fact that the thread which actually exits when stopping is not the thread which registered the service with the Windows Service Control Manager, and as I said, I am not sure if this problem can actually be fixed.

Steve

**Comment by divishav** [comment]
Hi @stephenwvickers , Thank you for your reply. So what do you suggest needs to be done to solve this issue?

**Comment by stephenwvickers** [comment]
Hi @divishav please see my last.

**Comment by divishav** [comment]
Hi @stephenwvickers , so you are saying this issue cannot be fixed, am I correct?

**Comment by stephenwvickers** [comment]
@divishav What I am saying is that I don't know what needs to be done to fix it, and there is a strong chance it relates to how we run Node.js under the Service Control Manager and so can never be fixed.

**Comment by s-h-a-d-o-w** [comment]
At least based on what I've just seen, this merely seems to stem from a mistake in the example:
```js
service.run (logStream, function () {
```

`run()` does not take a stream as the first argument. If it is removed, stopping the service works without errors.

**Comment by stephenwvickers** [comment]
@s-h-a-d-o-w I believe you are right. This would explain it.  I will update the example.
